# Generated by Django 5.2.1 on 2025-05-31 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_consumer_points'),
        ('credits', '0002_alter_product_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemptioncode',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='兑换时间'),
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='订单编号')),
                ('quantity', models.PositiveIntegerField(verbose_name='数量')),
                ('total_points', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总福力')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('shipped', '已发货'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='订单状态')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='物流单号')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.shipping', verbose_name='收货地址')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='credits.product', verbose_name='商品')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='credits.productspec', verbose_name='商品规格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_orders', to=settings.AUTH_USER_MODEL, verbose_name='用户订单')),
            ],
            options={
                'verbose_name': '兑换订单',
                'verbose_name_plural': '兑换订单',
                'ordering': ['-created_at'],
            },
        ),
    ]
