# Generated by Django 5.2.1 on 2025-06-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_alter_redemptioncode_used_at_exchangeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeorder',
            name='express_name',
            field=models.CharField(blank=True, choices=[('顺丰速运', '顺丰速运'), ('京东物流', '京东物流'), ('中通快递', '中通快递'), ('圆通速递', '圆通速递'), ('申通快递', '申通快递'), ('韵达快递', '韵达快递'), ('百世快递', '百世快递'), ('邮政快递', '邮政快递'), ('德邦快递', '德邦快递'), ('极兔速递', '极兔速递')], max_length=50, null=True, verbose_name='快递公司'),
        ),
    ]
