# Generated by Django 5.2.1 on 2025-06-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_exchangeorder_express_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.IntegerField(verbose_name='福力变动'),
        ),
        migrations.AlterField(
            model_name='product',
            name='points_required',
            field=models.PositiveIntegerField(verbose_name='所需福力'),
        ),
        migrations.AlterField(
            model_name='productspec',
            name='points_required',
            field=models.PositiveIntegerField(verbose_name='所需福力'),
        ),
        migrations.AlterField(
            model_name='redemptioncode',
            name='points_value',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='福力值'),
        ),
    ]
