# Generated by Django 5.2.1 on 2025-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0005_alter_pointstransaction_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(null=True, upload_to='products/%Y%m%d/', verbose_name='头图'),
        ),
    ]
