# Generated by Django 5.1.6 on 2025-03-09 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('series', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Redeem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=19, unique=True, verbose_name='兑换码')),
                ('status', models.SmallIntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('prize', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeems', to='series.prize', verbose_name='奖品')),
            ],
            options={
                'verbose_name': '兑换码',
                'verbose_name_plural': '兑换码',
                'db_table': 'redeems',
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('express_order', models.CharField(blank=True, max_length=30, null=True, verbose_name='快递单号')),
                ('status', models.SmallIntegerField(choices=[(0, '未发货'), (1, '已发货'), (2, '已收货')], default=0, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('consumer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='series.prize', verbose_name='奖品')),
                ('redeem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redemption', to='redeem.redeem', verbose_name='兑换码')),
                ('shipping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='account.shipping', verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'db_table': 'redemptions',
            },
        ),
    ]
