# Generated by Django 5.1.6 on 2025-03-15 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_shipping_city_alter_shipping_district_and_more'),
        ('redeem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping', to='account.shipping', verbose_name='收货地址'),
        ),
    ]
