# Generated by Django 5.1.6 on 2025-03-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0002_alter_redemption_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='express_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='快递公司'),
        ),
        migrations.AlterField(
            model_name='redemption',
            name='express_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='快递单号'),
        ),
    ]
