# Generated by Django 5.1.6 on 2025-03-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0003_redemption_express_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redemption',
            name='express_name',
            field=models.CharField(blank=True, choices=[('顺丰速运', '顺丰速运'), ('京东物流', '京东物流'), ('中通快递', '中通快递'), ('圆通速递', '圆通速递'), ('申通快递', '申通快递'), ('韵达快递', '韵达快递'), ('百世快递', '百世快递'), ('邮政快递', '邮政快递'), ('德邦快递', '德邦快递'), ('极兔速递', '极兔速递')], max_length=50, null=True, verbose_name='快递公司'),
        ),
    ]
