# Generated by Django 5.1.6 on 2025-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0004_alter_redemption_express_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redeem',
            options={'verbose_name': '抽奖码', 'verbose_name_plural': '抽奖码'},
        ),
        migrations.AlterField(
            model_name='redeem',
            name='number',
            field=models.CharField(max_length=19, unique=True, verbose_name='抽奖码'),
        ),
    ]
