# Generated by Django 5.2.1 on 2025-06-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0005_alter_redeem_options_alter_redeem_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='抽奖码'),
        ),
    ]
