# Generated by Django 5.2.1 on 2025-06-05 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redeem', '0006_alter_redeem_number'),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeems', to='series.series', verbose_name='系列'),
        ),
    ]
