# Generated by Django 5.1.6 on 2025-03-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='省份'),
        ),
    ]
