# Generated by Django 5.1.6 on 2025-05-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_shipping_city_alter_shipping_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='积分余额'),
        ),
    ]
