# Generated by Django 5.2.1 on 2025-08-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_consumer_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='微信关联号'),
        ),
    ]
