# Generated by Django 5.2.1 on 2025-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_consumer_openid'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='sales_rep',
            field=models.BooleanField(default=False, verbose_name='销售顾问'),
        ),
    ]
