# Generated by Django 5.2.1 on 2025-07-22 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='门店名称')),
                ('address', models.CharField(max_length=200, verbose_name='详细地址')),
                ('employee', models.CharField(max_length=20, verbose_name='员工姓名')),
                ('status', models.BooleanField(default=False, verbose_name='审核状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('consumer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_store', to=settings.AUTH_USER_MODEL, verbose_name='员工')),
            ],
            options={
                'verbose_name': '门店信息',
                'verbose_name_plural': '门店信息',
                'db_table': 'branch_stores',
            },
        ),
    ]
