# Generated by Django 5.2.1 on 2025-07-23 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
        ('redeem', '0007_redeem_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='兑换码')),
                ('status', models.BooleanField(default=False, verbose_name='使用状态')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='兑换金额')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('redeem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_redemption', to='redeem.redeem', verbose_name='抽奖码')),
            ],
            options={
                'verbose_name': '现金兑换码',
                'verbose_name_plural': '现金兑换码',
                'db_table': 'cash_redemptions',
            },
        ),
    ]
