# Generated by Django 5.2.1 on 2025-07-28 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_cashredemption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='兑换金额')),
                ('status', models.CharField(choices=[('pending', '待提现'), ('completed', '已提现')], default='pending', max_length=20, verbose_name='兑换状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('withdrawal_at', models.DateTimeField(blank=True, null=True, verbose_name='提现时间')),
                ('redemption', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.cashredemption', verbose_name='兑换码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '兑换记录',
                'verbose_name_plural': '兑换记录',
                'db_table': 'cash_exchanges',
                'ordering': ['-withdrawal_at'],
            },
        ),
    ]
