# Generated by Django 5.2.1 on 2025-08-09 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_cashexchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashexchange',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='流水编号'),
        ),
        migrations.AlterField(
            model_name='cashexchange',
            name='status',
            field=models.CharField(choices=[('pending', '待提现'), ('processing', '提现中'), ('completed', '已提现')], default='pending', max_length=20, verbose_name='兑换状态'),
        ),
        migrations.AlterField(
            model_name='cashexchange',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='cashredemption',
            name='cash',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='奖励金额'),
        ),
    ]
