# Generated by Django 5.2.1 on 2025-08-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_cashexchange_number_alter_cashexchange_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashexchange',
            name='number',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='流水编号'),
        ),
    ]
