# Generated by Django 5.2.1 on 2025-08-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_alter_cashexchange_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True, verbose_name='邀请码')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '销售邀请码',
                'verbose_name_plural': '销售邀请码',
            },
        ),
    ]
