# Generated by Django 5.1.6 on 2025-03-09 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('logo', models.ImageField(null=True, upload_to='series/%Y%m%d/', verbose_name='头图')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
                'db_table': 'series',
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('logo', models.ImageField(null=True, upload_to='prizes/%Y%m%d/', verbose_name='头图')),
                ('inventory', models.IntegerField(null=True, verbose_name='库存数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('series', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='series.series', verbose_name='系列')),
            ],
            options={
                'verbose_name': '奖品',
                'verbose_name_plural': '奖品',
                'db_table': 'prizes',
            },
        ),
    ]
