# Generated by Django 5.2.1 on 2025-06-25 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='店铺名称')),
                ('address', models.CharField(max_length=500, verbose_name='详细地址')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('description', models.TextField(blank=True, verbose_name='店铺描述')),
                ('latitude', models.FloatField(help_text='店铺所在位置的纬度', verbose_name='纬度')),
                ('longitude', models.FloatField(help_text='店铺所在位置的经度', verbose_name='经度')),
                ('business_hours', models.CharField(blank=True, max_length=100, verbose_name='营业时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否营业')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺管理',
                'ordering': ['-created_at'],
            },
        ),
    ]
