# Generated by Django 5.2.1 on 2025-07-03 09:47

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_plush'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plush',
            options={'ordering': ['-is_latest'], 'verbose_name': '每期周边', 'verbose_name_plural': '每期周边'},
        ),
        migrations.AlterField(
            model_name='plush',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plush',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='plush/%Y%m%d/', verbose_name='图床链接'),
        ),
        migrations.AlterField(
            model_name='plush',
            name='name',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
