# Generated by Django 5.2.1 on 2025-07-09 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_plush_options_alter_plush_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plush',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='详情内容'),
        ),
    ]
