# Generated by Django 5.2.1 on 2025-07-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_alter_plush_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='navigation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='导航地名'),
        ),
    ]
