# Generated by Django 5.2.1 on 2025-07-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='navigation',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='导航地址'),
        ),
    ]
