# Generated by Django 5.2.1 on 2025-08-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_store_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plush',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='plush/%Y%m%d/', verbose_name='头图'),
        ),
    ]
